name = "Simplex"
uuid = "e86195cf-c81c-48b7-a052-95ab1649ce81"
authors = ["Raul Britto"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
